### ISSUE TITLE
Add default view.

### ISSUE THREAD

**Issue by gaelL** [guits/pastefile#5] opened 2015-11-02 21:08 UTC
When we try a random url we have an error : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

Try to add a custom `404` page that print of a help page.

**Comment by guits** [comment] 2015-11-06 07:28
Duplicate of issue #8 
A custom 404 error page has been added in c72e133

**Closed as completed by guits** 2015-11-06 07:28 UTC
Labels: duplicate
